// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8cQhQhZzuw8bMsM3ou9deJy5RbPhePZI',
    appId: '1:313804114303:web:bc4b777bb5c24bf0a8724a',
    messagingSenderId: '313804114303',
    projectId: 'uth-smarttasks-truc-52b6d',
    authDomain: 'uth-smarttasks-truc-52b6d.firebaseapp.com',
    storageBucket: 'uth-smarttasks-truc-52b6d.firebasestorage.app',
    measurementId: 'G-W0F5Q8Q3LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzUEuDOaT7Gy0lDLwNGf_1d9lSiBi-v8k',
    appId: '1:313804114303:android:bd7c42d8008582f7a8724a',
    messagingSenderId: '313804114303',
    projectId: 'uth-smarttasks-truc-52b6d',
    storageBucket: 'uth-smarttasks-truc-52b6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ-OKbRhcB0-OHMca5zzFTTxExllMZezY',
    appId: '1:313804114303:ios:a59b3e1cdc4c2d41a8724a',
    messagingSenderId: '313804114303',
    projectId: 'uth-smarttasks-truc-52b6d',
    storageBucket: 'uth-smarttasks-truc-52b6d.firebasestorage.app',
    iosBundleId: 'com.example.sourcecode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ-OKbRhcB0-OHMca5zzFTTxExllMZezY',
    appId: '1:313804114303:ios:a59b3e1cdc4c2d41a8724a',
    messagingSenderId: '313804114303',
    projectId: 'uth-smarttasks-truc-52b6d',
    storageBucket: 'uth-smarttasks-truc-52b6d.firebasestorage.app',
    iosBundleId: 'com.example.sourcecode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8cQhQhZzuw8bMsM3ou9deJy5RbPhePZI',
    appId: '1:313804114303:web:eefadc8e4a66eeeea8724a',
    messagingSenderId: '313804114303',
    projectId: 'uth-smarttasks-truc-52b6d',
    authDomain: 'uth-smarttasks-truc-52b6d.firebaseapp.com',
    storageBucket: 'uth-smarttasks-truc-52b6d.firebasestorage.app',
    measurementId: 'G-NEEKKDT3BG',
  );
}
